server/todo/urls.py
from django.urls import path

from todo import views

app_name = "todo"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("profile/<str:username>", views.profile_view, name="profile"),
]

server/webapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
]

server/todo/models.py
from django.db import models


class ToDoList(models.Model):
    name = models.CharField(max_length=256)
    items: models.Manager["ToDoItem"]

    def incomplete_count(self):
        return self.items.filter(completed=False).count()

    def __str__(self) -> str:
        return self.name


class ToDoItem(models.Model):
    list = models.ForeignKey(ToDoList, on_delete=models.CASCADE, related_name="items")
    item = models.CharField(max_length=256)
    completed = models.BooleanField()

    def __str__(self) -> str:
        return self.item


class Profile(models.Model):
    username = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    description = models.TextField()

server/todo/views.py
from django.db import connection
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseNotFound
from django.views import generic

from todo.models import ToDoList


class IndexView(generic.ListView):
    template_name = "todo/index.html"

    def get_queryset(self) -> QuerySet[ToDoList]:
        return ToDoList.objects.all()


class DetailView(generic.DetailView):
    model = ToDoList
    template_name = "todo/list.html"


def profile_view(request: HttpRequest, username: str) -> HttpResponse:
    with connection.cursor() as cursor:
        # NOTE: Explicitly vulnerable to SQL Injection for demo purposes
        cursor.execute(f"SELECT name, description FROM todo_profile WHERE username = '{username}'")
        row = cursor.fetchone()

    if row:
        name = row[0]
        description = row[1]
    else:
        return HttpResponseNotFound()

    return HttpResponse(
        f"""
        <!DOCTYPE html>
        <html>
            <head>
                <title>To-Do lists</title>

                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
            </head>
            <body>
                <div class="container">
                    <div class="row my-5">
                        <div class="col"><h1>Profile</h1></div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <p>Name</p>
                        </div>
                        <div class="col">
                            <p>{name}</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <p>Description</p>
                        </div>
                        <div class="col">
                            <p>{description}</p>
                        </div>
                    </div>
                </div>
            </body>
        </html>
        """
    )

server/todo/templates/todo/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}To-Do lists{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

server/todo/templates/todo/index.html
{% extends "todo/base.html" %}

{% block content %}
<div class="row my-5">
    <div class="col"><h1>To-not-Do</h1></div>
</div>

<div class="row">
    <div class="col">
        <div class="list-group">
        {% for todolist in todolist_list %}
            <a class="list-group-item list-group-item-action d-flex" href="{% url 'todo:detail' todolist.id %}">
                <div class="me-auto">{{ todolist.name }}</div>
                <span class="badge text-bg-primary rounded-pill">{{ todolist.incomplete_count }}</span>
            </a>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

server/todo/templates/todo/list.html
{% extends "todo/base.html" %}

{% block content %}
<div class="row my-5">
    <div class="col">
        <h1>{{ todolist.name }}</h1>
    </div>
    <div class="col-2 d-flex align-items-center justify-content-end">
        <a class="btn btn-outline-primary" href="{% url 'todo:index' %}">Back</a>
    </div>
</div>

<form method="post">
    {% csrf_token %}
    <input id="item" name="item" type="text" />
    <button type="submit">Toevoegen</button>
</form>

<div class="row">
    <div class="col">
        <ul class="list-group">
            {% for todoitem in todolist.items.all %}
                <li class="list-group-item">{{ todoitem.item }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}